--- 
- 
  connection: network_cli
  gather_facts: false
  hosts: oob-switches
  name: "Cisco show running-config on ios"
  tasks: 
    - name: running show command
      ios_command:
        commands:
        - show run
        - show ip route
        - show ip eigrp neighbors
        - show version
      register: config
    - name: "Collect current  timestamp"
      register: timestamp
      run_once: true
      shell: "date +%Y%m%d"
    - name: "Create folder"
      file:
        path: ./backups/{{ timestamp.stdout }}
        state: directory
        mode: '0755'
    - name: checking if old files are present
      stat:
        path: "./backups/{{ timestamp.stdout }}/{{ inventory_hostname }}_config.txt"
      register: stat_result
    - name: Removing old files
      ansible.builtin.file:
        path: "./backups/{{ timestamp.stdout }}/{{ inventory_hostname }}_config.txt"
        state: absent
      when: stat_result.stat.exists
    - name: Save output to backups folder
      copy:
        content: "{{ config.stdout | regex_replace('\\n', '\n') }}"
        dest: "./backups/{{ timestamp.stdout }}/{{ inventory_hostname }}_config.txt"
...
